"""add nomnoms column

Revision ID: 3ba1ba4fa179
Revises: ce6ed5e0efd8
Create Date: 2025-11-12 00:25:29.869848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba1ba4fa179'
down_revision: Union[str, Sequence[str], None] = 'ce6ed5e0efd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nomnoms', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nomnoms')
    # ### end Alembic commands ###
