"""keep track of cogifting vs recipient msg for anon

Revision ID: 5598976d5ed2
Revises: 67532cf60d46
Create Date: 2025-10-30 23:41:05.713629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5598976d5ed2'
down_revision: Union[str, Sequence[str], None] = '67532cf60d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_santa_message_logs', sa.Column('to_gift_recipient', sa.Boolean(), nullable=True, server_default=sa.true()))

    op.execute(
        sa.text("UPDATE secret_santa_message_logs SET to_gift_recipient = :val WHERE to_gift_recipient IS NULL").bindparams(val=False)
    )
    op.alter_column('secret_santa_message_logs',
                    'to_gift_recipient',
                    nullable=False,
                    server_default=None
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret_santa_message_logs', 'to_gift_recipient')
    # ### end Alembic commands ###
