"""add a table to log messages to remember their author and origin

Revision ID: 67532cf60d46
Revises: 0df37fa272f0
Create Date: 2025-10-30 00:02:21.134397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67532cf60d46'
down_revision: Union[str, Sequence[str], None] = '0df37fa272f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_santa_message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_discord_channel_id', sa.String(), nullable=False),
    sa.Column('discord_message_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_santa_message_logs')
    # ### end Alembic commands ###
