"""make secret santa context guild id not unique

Revision ID: ce6ed5e0efd8
Revises: 5598976d5ed2
Create Date: 2025-11-11 22:10:09.703425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6ed5e0efd8'
down_revision: Union[str, Sequence[str], None] = '5598976d5ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('secret_santa_contexts_guild_id_key'), 'secret_santa_contexts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('secret_santa_contexts_guild_id_key'), 'secret_santa_contexts', ['guild_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
